backend:
  name: github
  repo: vikhyaat12/your-repo-name
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Theme & Logo"
        name: "theme"
        file: "data/theme.json"
        fields:
          - { label: "Theme Color", name: "color", widget: "color" }
          - { label: "Logo", name: "logo", widget: "image" }
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Videos", name: "videos", widget: "list", required: false, field: {label: "Video URL", name: "url", widget: "string"} }
