backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content.json"
        label: "Portfolio Content"
        name: "portfolio_content"
        fields:
          - { label: "Profile Image", name: "profile_img", widget: "image" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Story", name: "story", widget: "markdown" }
          - { label: "Expertise", name: "expertise", widget: "string" }
          - label: "Achievements"
            name: "achievements"
            widget: "list"
            fields:
              - { label: "Icon (FontAwesome class)", name: "icon", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "desc", widget: "string" }
          - { label: "Case Studies", name: "caseStudies", widget: "markdown" }
          - { label: "Quote", name: "quote", widget: "string" }
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Email", name: "email", widget: "string" }
              - { label: "LinkedIn", name: "linkedin", widget: "string" }
              - { label: "Instagram", name: "instagram", widget: "string" }
              - { label: "WhatsApp", name: "whatsapp", widget: "string" }
              - { label: "WhatsApp Message", name: "whatsappMsg", widget: "string" }
